### ISSUE TITLE
Task: data-augmentation peer review and testing

### ISSUE THREAD

**Issue by ibevers** [sensein/senselab#101]
### Description

Test feedback: 
- Use the global fixtures
- Test could use more descriptive comment

"torch-audiomentations is in a very early development stage, so it's not ready for prime time yet. Meanwhile, star the repo and stay tuned!"
https://pypi.org/project/torch-audiomentations/0.1.0/

### Tasks

Additional tests:
- [x] Test more augmentations for audiomentations
- [x] Test with silence-only audio.
- [x] Test with noise-only audio.
- [x] Test with a combination of augmentations.
- [x] Test an empty audio file and a very short audio file.

**Comment by ibevers** [comment]
A lot of long lines in data_augmentation.py (have to pan to see all the code)--this is true elsewhere, so we might want to consider making our line length restrictions more stringent.

**Comment by ibevers** [comment]
> "torch-audiomentations is in a very early development stage, so it's not ready for prime time yet. Meanwhile, star the repo and stay tuned!" https://pypi.org/project/torch-audiomentations/0.1.0/

Consider adding a warning about this, so people don't assume that it is more reliable than it is.
