### ISSUE TITLE
Task: Audio summary

### ISSUE THREAD

**Issue by satra** [sensein/senselab#139]
### Description

Provide a JSON dictionary (with a proper schema) describing the audio that we can extend as we need more elements in the summary. 

### Tasks

- [x] duration
- [x] sampling rate
- [x] encoding
- [x] channels
- [x] mono/stereo estimation for two channel recording
- [ ] background noise level - stats
- [ ] Estimated number of speakers
- [ ] Contains speech (if yes, which languages)

### Freeform Notes

The intent is to quickly see a set of metadata about an audio file. Do suggest additional features as relevant.

**Comment by fabiocat93** [comment]
I have started drafting this method in the dev branch. We will need to brainstorm what info is relevant to include here
