### ISSUE TITLE
Modularize dependencies into audio vs video vs text

### ISSUE THREAD

**Issue by 900miles** [sensein/senselab#145]
### Description

As our list of dependencies grows longer and longer, we should think about how to best manage them. A good start might be to split them into three categories: audio, video, and text, so that users can install only the dependencies they plan to use. In the future we may need to further break them apart further into task-level modularization.

### Tasks

- [ ] Determine which dependencies fall into the categories: `core`, `audio`, `video`, and `text`
- [ ] Update `pyproject.yaml` accordingly
- [ ] Update `README.txt` with installation instructions
- [ ] Add decorator or some other feature to interfaces to indicate that it cannot be imported because a dependency is missing.
