### ISSUE TITLE
[Task] Extend the list of supported audio features

### ISSUE THREAD

**Issue by fabiocat93** [sensein/senselab#193]
## Description
We want to expand the audio features that `senselab` can extract. This will include:
- Time-varying features: Features that provide detailed information about audio properties over time.
- Aggregated features: Statistical or summarized representations of audio properties (e.g., min, max, range, mean pitch, standard deviation of feature X).

## Tasks
- [ ] Research and shortlist additional audio features (time-varying and aggregated).
- [ ] Define how these features will be implemented in senselab.
- [ ] Update senselab's feature extraction API to include the new features.
- [ ] Write tests to ensure the correctness and reliability of the new features.
- [ ] Update documentation to reflect the changes.

**Comment by fabiocat93** [comment]
**Let's start by using this space to discuss features of interest.**

**Comment by fabiocat93** [comment]
about **time-varing feats**: @satra (from a slack conv) suggested:
- [ ] formants
- [ ] pitch
- [ ] intensity
- [ ] loudness
- [ ] glottal flow (derivative of)
- [ ] vad (this should detect any vocalizations)
- [ ] non-vocal fold source (aspiration/frication)

@fabiocat93 added (also inspired by @Rahul-Brito 's slides - of course, @Rahul-Brito feel free to add and comment further)
- [ ] Energy
- [ ] Perceptual Linear Predictive (PLP)
- [ ] Linear Predictive Coding (LPC)
- [ ] Line Spectral Pairs (LSP)
- [ ] Spectral Shape descriptors (Spectral centroid, Spectral bandwidth, ...)
- [ ] Harmonics-to-Noise Ratio (and maybe speech to noise ration - here is an interesting model for estimating it: https://huggingface.co/pyannote/brouhaha)

**Comment by fabiocat93** [comment]
here are some _good_ resources that i have filtered and may be helpful since they come with their own implementations:

-  https://github.com/Shahabks/my-voice-analysis
- https://github.com/Shahabks/myprosody
- https://osf.io/3wr6k/files/osfstorage
- https://voice-lab.github.io/VoiceLab/#documentation-and-api-reference
- https://osf.io/huz7d/
- https://github.com/drfeinberg/PraatScripts/blob/master/Measure%20Pitch%20and%20HNR.ipynb
- https://github.com/drfeinberg/PraatScripts/blob/master/Measure%20Pitch%2C%20HNR%2C%20Jitter%2C%20Shimmer%2C%20and%20Formants.ipynb
- https://github.com/drfeinberg/PraatScripts/blob/master/Measure%20Pitch%2C%20HNR%2C%20Jitter%2C%20and%20Shimmer.ipynb
- https://github.com/drfeinberg/PraatScripts/blob/master/spectral_tilt.py
- https://github.com/drfeinberg/PraatScripts/blob/master/syllable_nuclei.py

**Comment by fabiocat93** [comment]
also, it may be cool to have some functions for plotting (parselmouth) feats like in [here](https://parselmouth.readthedocs.io/en/stable/examples/plotting.html)

**Comment by fabiocat93** [comment]
Also, @skirdey open-sourced some [code](https://github.com/skirdey/SonicStats) for audio metrics calculation of PESQ, CSIG, CBAK, COVL, STOI. It may be interesting to make those feats part of senselab (some we already have).

**Comment by satra** [comment]
>  audio metrics calculation of PESQ, CSIG, CBAK, COVL, STOI

`pesq` and `stoi` are already computed by torchaudio_squim. perhaps add the others to that section/workflow.

**Comment by fabiocat93** [comment]
here are some more good feats we may want to include (they have shown some usefulness for Alzheimer detection): https://github.com/Annafavaro/TAUKADIAL-2024

**Comment by fabiocat93** [comment]
related subissues:
- https://github.com/sensein/senselab/issues/160
- https://github.com/sensein/senselab/issues/159
- https://github.com/sensein/senselab/issues/158
- https://github.com/sensein/senselab/issues/157
- https://github.com/sensein/senselab/issues/156
- https://github.com/sensein/senselab/issues/155
- https://github.com/sensein/senselab/issues/154

**Comment by fabiocat93** [comment]
@wilke0818 found this other interesting tool: https://github.com/jcvasquezc/DisVoice
