### ISSUE TITLE
Task: Audio I/O

### ISSUE THREAD

**Issue by fabiocat93** [sensein/senselab#199]
### Description

We miss a function to save the audio to a file, specifying bit depth, encoding, and format;
We also need functions to read and write audio files parallelly. 

### Tasks

- [x] Implement a function in the Audio class for saving the audio to file
- [x] Implement a function for reading multiple audio files in parallel
- [x] Implement a function for writing multiple audio files in parallel
