### ISSUE TITLE
Task: Preprocessing

### ISSUE THREAD

**Issue by fabiocat93** [sensein/senselab#24]
### Description

Preprocess audio data by resampling, transforming stereo to mono (via downmix or channel selection), chunking based on start and end timestamps, extracting audio from video, and performing audio data augmentation.

### Tasks

- [x] resampling, 
- [x] transforming stereo to mono (via downmix or channel selection),
- [x] chunking based on start and end timestamps, 
- [ ] extracting audio from video, 
- [x] #43

**Comment by wilke0818** [comment]
is audio loudness normalization a standard preprocessing that we should do or is it specific to the task (e.g. emotion classification)?

**Comment by fabiocat93** [comment]
> is audio loudness normalization a standard preprocessing that we should do or is it specific to the task (e.g. emotion classification)?

you can see loudness normalization as a specific type of data augmentation
