### ISSUE TITLE
Task: Data representation

### ISSUE THREAD

**Issue by fabiocat93** [sensein/senselab#25]
### Description

Extracting audio self-supervised models' embeddings, supervised model's speaker embeddings (xvector, ECAPA-TDNN, ResNet), acoustic features, linguistic features, and text self-supervised model's embeddings.

### Tasks

- [x] Extracting audio self-supervised models' embeddings @GasserElbanna , 
- [x] Extracting text self-supervised model's embeddings,
- [x] Extracting supervised model's speaker embeddings (xvector, ECAPA-TDNN, ResNet) @900miles , 
- [ ] Extracting handcrafted features (opensmile, praat, torchaudio - including spectrogram - and consider integrating features from [Nick’s table](https://docs.google.com/spreadsheets/d/18V_FrE3jYm1Msl4rg8xl8WVBDprbZrRFIVm3nEf2uTQ/edit?usp=sharing) and [Daniel's paper](https://onlinelibrary.wiley.com/doi/pdf/10.1002/lio2.354) in the future),
- [ ] Extracting linguistic features.
