### ISSUE TITLE
Task: Utilities

### ISSUE THREAD

**Issue by fabiocat93** [sensein/senselab#30]
### Description

Implement utility functions for computing Word Error Rate (WER), cosine similarity between embeddings, Equal Error Rate (EER), Centered Kernel Alignment (CKA), Canonical Correlation Analysis (CCA), dimensionality reduction (PCA, t-SNE, UMAP), and cross-correlation between two signals.

### Tasks

- [x] Computing Word Error Rate (WER), 
- [x] Computing cosine similarity between embeddings, 
- [x] Computing Equal Error Rate (EER), 
- [x] Computing Centered Kernel Alignment (CKA), 
- [x] Computing Canonical Correlation Analysis (CCA), 
- [x] Computing cross-correlation between two signals.
