### ISSUE TITLE
Task: adding a pipeline for the ALI project

### ISSUE THREAD

**Issue by fabiocat93** [sensein/senselab#46]
### Description

adding a pipeline for the ALI project

### Tasks

- [ ] speech to text
- [ ] forced alignment
- [ ] speaker diarization
- [ ] facial action units extraction
- [ ] facial emotion recognition
- [ ] text emotion/sentiment analysis
- [ ] speech emotion analysis
- [ ] text semantic embeddings extraction

**Comment by fabiocat93** [comment]
@meralha I will close this issue for now since it seems to me that this is more like a separate project that may exploit senselab than a feature of the package (but feel free to open it again if you feel it should stay open).
