### ISSUE TITLE
Task: Add diarization tests

### ISSUE THREAD

**Issue by ibevers** [sensein/senselab#72]
### Description

Add at least three tests to speaker diarization.

### Tasks

- [ ] test _annotation_to_dict empty input 
- [ ] test _annotation_to_dict single input 
- [ ] test _annotation_to_dict longer input 
- [ ] validate correct tensor transformation and shape adjustments _pyannote_diarize_batch
- [ ] correct output with each model type
- [ ] check diarizations same with batch true and batch false
